### ISSUE TITLE
webview.dll': error code -2090870520

### ISSUE THREAD

**Issue by fabio21** [shreyassanthu77/webview_dart#1]
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
Debug service listening on ws://127.0.0.1:52685/dpwWYwcce8M=/ws
Syncing files to device Windows...

======== Exception caught by gesture ===============================================================
The following ArgumentError was thrown while handling a gesture:
Invalid argument(s): Failed to load dynamic library 'C:/dart_templetes/xxxx/webview.dll': error code -2090870520

```
When the exception was thrown, this was the stack: 
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      loadLibrary (package:webview_dart/src/bindings.dart:46:33)
#3      Webview._lib (package:webview_dart/src/webview_dart_api.dart:15:34)
#4      Webview._lib (package:webview_dart/src/webview_dart_api.dart)
#5      Webview._create (package:webview_dart/src/webview_dart_api.dart:21:55)
#6      Webview._create (package:webview_dart/src/webview_dart_api.dart)
#7      new Webview (package:webview_dart/src/webview_dart_api.dart:40:15)
#8      _MyHomePageState.webView (package:msal_windows/main.dart:119:5)
#9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#13     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#14     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443:20)
#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#25     _invoke1 (dart:ui/hooks.dart:169:10)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#7fd04
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(1221.0, 643.0)
  finalLocalPosition: Offset(29.0, 34.0)
  button: 1
  sent tap down
====================================================================================================

```

**Comment by shreyassanthu77** [comment]
This package is not supposed to be used with flutter insted its jast a native webview to build desktop UI apps with web technologies
