### ISSUE TITLE
Unhandled Exception with not found webview.dylib

### ISSUE THREAD

**Issue by acoffeeworld** [shreyassanthu77/webview_dart#13]
How do I find the build instructions for the dylib file I want to compile myself
version: webview_dart: ^1.0.1
platform: macos 12.6.5
cpu: Apple M1

stack:
`#4      Webview._lib (package:webview_dart/src/webview_dart_api.dart)`
`#5      Webview._create (package:webview_dart/src/webview_dart_api.dart:20:55)`
`#6      Webview._create (package:webview_dart/src/webview_dart_api.dart)`
`#7      new Webview (package:webview_dart/src/webview_dart_api.dart:39:15)`
`#8      Global.getPlatformWebView (package:basefund/global.dart:98:7)`
`#9      SearchWidget.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:basefund/page/qhr/widgets/search.dart:118:50)`
`#10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)`
`#11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)`
`#12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)`
`#13     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:276:7)`
`#14     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:163:27)`
`#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:464:20)`
`#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)`
`#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:336:11)`
`#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)`
`#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)`
`#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)`
`#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)`
`#22     _invoke1 (dart:ui/hooks.dart:164:13)`
`#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)`
`#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)`

**Comment by shreyassanthu77** [comment]
[Click here](https://github.com/webview/webview_deno/releases/download/0.7.3/libwebview.aarch64.dylib) to download the dylib for aarch64

**Comment by acoffeeworld** [comment]
I added the dylib to application data file, but it was stuck when execute `var web = Webview(true);`
![image](https://github.com/shreyassanthu77/webview_dart/assets/17959717/e5cc53a0-7ea0-4f94-a0df-dd02e9c47aa2)

**Comment by shreyassanthu77** [comment]
Are you using flutter ?

**Comment by acoffeeworld** [comment]
yeah, Flutter 3.10.0,  Dart 3.0.0

**Comment by shreyassanthu77** [comment]
If you want to use it with flutter you should use isolates to launch the webview from a different thread so flutter can continue it's rendering
